import type { Metadata } from "next";
import "@/app/globals.css";
import AuthProvider from "@/app/provider";
import Sidebar from "@/components/shared/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body>
        <div className="flex">
            <Sidebar />
            <main className="ml-[60px] flex-1 p-4">
                <AuthProvider>{children}</AuthProvider>
            </main>
        </div>
      </body>
    </html>
  );
}
