on:
  push:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/colsaofrancisco-teste-www/htdocs/teste.www.colsaofrancisco.com.br/CSFA-FRONTEND
          git pull origin main
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          export PATH=$PATH:/usr/local/bin:/usr/bin
          source ~/.bashrc || source ~/.bash_profile || true
          npm install
          npm run build
          pm2 restart app || pm2 start ecosystem.config.js
